### ISSUE TITLE
unable to produce plan using module

### ISSUE THREAD

**Issue by paraglade** [rancher/terraform-rancher2-project#3]
```╷
│ Error: Invalid for_each argument
│ 
│   on .terraform/modules/metrics-project/main.tf line 108, in resource "rancher2_app_v2" "apps":
│  108:   for_each      = try({ for k, v in local.app_list : v.name => v }, {})
│     ├────────────────
│     │ local.app_list is tuple with 1 element
│ 
│ The "for_each" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many
│ instances will be created. To work around this, use the -target argument to first apply only the resources that the for_each
│ depends on.
╵
```

**Comment by paraglade** [comment]
TF code is here:
https://github.com/paraglade/rancher-it-infra/tree/EIO-592-setup-livestock-metrics-project

use of the `try` function might result in impure results that is documented here:
https://www.terraform.io/docs/language/meta-arguments/for_each.html#:~:text=for_each%20keys%20cannot%20be%20the%20result%20(or%20rely%20on%20the%20result%20of)%20of%20impure%20functions%2C%20including%20uuid%2C%20bcrypt%2C%20or%20timestamp%2C%20as%20their%20evaluation%20is%20deferred%20during%20the%20main%20evaluation%20step

the `try` function states that: `access to data that isn't known until runtime` as noted here:
https://www.terraform.io/docs/language/functions/try.html#:~:text=The%20try%20function%20can%20only%20catch%20and%20handle%20dynamic%20errors%20resulting%20from%20access%20to%20data%20that%20isn%27t%20known%20until%20runtime.%20It%20will%20not%20catch%20errors%20relating%20to%20expressions%20that%20can%20be%20proven%20to%20be%20invalid%20for%20any%20input%2C%20such%20as%20a%20malformed%20resource%20reference

I have an idea on how to fix this that I will test and if it works I will put in a PR.

**Comment by rawmind0** [comment]
Guessing the issue is caused by these assignments, https://github.com/paraglade/rancher-it-infra/blob/EIO-592-setup-livestock-metrics-project/cattleman/clusters/livestock/projects/metrics/project-metrics.tf#L86-L87

> use of the try function might result in impure results that is documented here:
https://www.terraform.io/docs/language/meta-arguments/for_each.html#:~:text=for_each%20keys%20cannot%20be%20the%20result%20(or%20rely%20on%20the%20result%20of)%20of%20impure%20functions%2C%20including%20uuid%2C%20bcrypt%2C%20or%20timestamp%2C%20as%20their%20evaluation%20is%20deferred%20during%20the%20main%20evaluation%20step

`for_each keys cannot be the result (or rely on the result of) of impure functions, including uuid, bcrypt, or timestamp, as their evaluation is deferred during the main evaluation step.`

I don't see where is talking about the `try` function in that case.

> the try function states that: access to data that isn't known until runtime as noted here:
https://www.terraform.io/docs/language/functions/try.html#:~:text=The%20try%20function%20can%20only%20catch%20and%20handle%20dynamic%20errors%20resulting%20from%20access%20to%20data%20that%20isn%27t%20known%20until%20runtime.%20It%20will%20not%20catch%20errors%20relating%20to%20expressions%20that%20can%20be%20proven%20to%20be%20invalid%20for%20any%20input%2C%20such%20as%20a%20malformed%20resource%20reference

Yes, this is the error that the terraform apply is stating.  Access to data that isn't known until runtime can't be accessed on the `app.value` field. The data should be injected like is done here, https://github.com/paraglade/rancher-it-infra/blob/EIO-592-setup-livestock-metrics-project/cattleman/clusters/livestock/projects/grafana/config/grafana/grafana-values.yaml#L27, using the private variable.
